

name: Release

on:
	push:
		tags:
			- 'v*.*.*'

jobs:
	build:
		name: Build and Release
		runs-on: ${{ matrix.os }}
		strategy:
			matrix:
				os: [ubuntu-latest, macos-latest, windows-latest]
				include:
					- os: ubuntu-latest
						artifact_name: wgo-linux
						build_cmd: cargo build --release
						binary_path: target/release/wgo
					- os: macos-latest
						artifact_name: wgo-macos
						build_cmd: cargo build --release
						binary_path: target/release/wgo
					- os: windows-latest
						artifact_name: wgo-windows.exe
						build_cmd: cargo build --release
						binary_path: target/release/wgo.exe
		steps:
			- name: Checkout code
				uses: actions/checkout@v4

			- name: Set up Rust
				uses: actions/setup-rust@v1
				with:
					rust-version: stable

			- name: Build release binary
				run: ${{ matrix.build_cmd }}

			- name: Rename binary for upload
				run: |
					if [ "${{ runner.os }}" = "Windows" ]; then
						mv target/release/wgo.exe ${{ matrix.artifact_name }}
					else
						mv ${{ matrix.binary_path }} ${{ matrix.artifact_name }}
					fi
				shell: bash

			- name: Upload release asset
				uses: softprops/action-gh-release@v2
				with:
					files: ${{ matrix.artifact_name }}
				env:
					GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
